### ISSUE TITLE
PWR Data Seed: YOSE Roads, Trails, Buildings

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#303] opened 2015-12-08 16:06 UTC
Sandy from PWR requested that we seed the following data for Yosemite using her published services:
- Roads
- Trails
- Buildings (from facilities)

Feature Server: [http://inppwcagis01:6080/arcgis/rest/services/PWR](http://inppwcagis01:6080/arcgis/rest/services/PWR)

**Comment by jakecoolidge** [comment] 2016-04-17 13:52
Vanessa also requested we pull in current POIs for YOSE. Here's the breakdown of translations of the GIS attributes to Places tags:

| GIS attribute | action | Places tag | comment |
| --- | --- | --- | --- |
| CREATEUSER | removed |  |  |
| DISTRIBUTE | removed |  |  |
| EDITUSER | removed |  |  |
| FEATUREID | removed |  |  |
| GEOMETRYID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value | one of two fields with a unique id for each feature |
| ISEXTANT | removed |  |  |
| MAPMETHOD | removed |  |  |
| NOTES | retained | nps:notes |  |
| OBJECTID | removed |  | one of two fields with a unique id for each feature, selected GlobalID as unique identifier |
| POIALTNAME | retained | alt_name |  |
| POIFEATTYP | removed |  |  |
| POILABEL | removed |  | appears to be a duplicate of POINAME |
| POINAME | retained | name |  |
| POITYPE | removed after tags were assigned | 23 unique values, see table below |  |
| REGIONCODE | removed |  |  |
| RESTRICTIO | removed |  |  |
| UNITCODE | retained | 'nps:unit_code'='yose' |  |
| XYERROR | removed |  |  |
|  | added | 'nps:source_system'='PWR_NPS_PointsOfInterest, accessed 2016-04-17' |  |
|  | added | 'nps:source_system_key'='GlobalID' |  |

| POITYPE value | count | Places tag(s) |
| --- | --- | --- |
| Backcountry Campsite | 9 | {"tourism":"camp_site","camp_site":"pitch","backcountry":"yes"} |
| Campground | 15 | {"tourism":"camp_site"} |
| Campground Kiosk | 10 | {"tourism":"information","information":"board"} |
| Campsite | 1219 | {"tourism":"camp_site","camp_site":"pitch"} |
| Church | 1 | {"building":"church"} |
| Entrance Station | 9 | {"barrier":"entrance"} |
| Food Service | 11 | {"amenity":"food_court"} |
| Gas Station | 4 | {"amenity":"fuel"} |
| Hospital | 1 | {"amenity":"hospital"} |
| Lodging | 781 | {"tourism":"hotel"} |
| Market | 5 | {"shop":"general"} |
| Museum | 3 | {"tourism":"museum"} |
| Other | 41 | see next table |
| Parking Lot | 259 | {"amenity":"parking"} |
| Picnic Area | 18 | {"tourism":"picnic_site"} |
| Post Office | 3 | {"amenity":"post_office"} |
| Private Residence Rental | 120 | {"building":"residential"} |
| Public Restroom | 31 | {"amenity":"toilets"} |
| Restroom | 96 | {"amenity":"toilets","access":"permissive"} |
| Stable | 1 | {"building":"stable"} |
| Store | 2 | {"shop":"general"} |
| Trailhead | 65 | {"highway":"trailhead"} |
| Visitor Center | 5 | {"tourism":"information","information":"office"} |

**POITYPE="Other"**

| POINAME | Count | Places tag(s) | Comment |
| --- | --- | --- | --- |
| Anderson's Cabin | 1 | {"building":"cabin","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Army Cabin | 1 | {"building":"cabin","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Army Tack Room | 1 | {"building":"yes","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Artists Cabin (C Jorgensen) | 1 | {"building":"cabin","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Badger Pass Backcountry Shop | 1 | {"shop":"general"} |  |
| Badger Pass Ski Rental Shop | 1 | {"shop":"general"} |  |
| Bike Repair Shop | 1 | {"shop":"general"} |  |
| Blacksmith Shop | 1 | {"building":"yes","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Carriage Shop | 1 | {"building":"yes","historic":"yes"} | see [this link](http://www.hscl.cr.nps.gov/insidenps/report.asp?STATE=CA&PARK=YOSE&STRUCTURE=&SORT=2&RECORDNO=23) |
| Curry Village Lounge | 1 | {"building":"yes"} |  |
| DNC Wawona stables | 1 | {"building":"stable"} |  |
| Degnan's Bakery | 1 | {"building":"yes","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Happy Isles Nature Center | 1 | {"tourism":"museum"} | see [this](https://www.nps.gov/yose/planyourvisit/historic.htm) |
| Hodgdon Homestead Cabin | 1 | {"building":"cabin","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Le Conte Memorial HIstoric Lodge | 1 | {"building":"yes","historic":"yes"} |  |
| Lower Pines Amphitheater seating | 3 | {"amenity":"theatre","theatre:type":"amphi"} | assigned the amphitheater to the central seating area; flanking seating areas assigned {"amenity":"bench"} |
| Lower Pines Amphitheater stage | 1 | {"amenity":"theatre","theatre:stage":"yes"} | see [this](https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dtheatre#open_air_theatre) |
| Lower Pines Amphitheater tech rm | 1 | {"building":"yes"} |  |
| Lower River Amphitheater | 3 | {"building":"yes"} | these are buildings surrounding the amphitheater |
| Lower River Amphitheater Stage | 1 | {"amenity":"theatre","theatre:stage":"yes"} | see [this](https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dtheatre#open_air_theatre) |
| Stables Farrier | 1 | {"building":"stable"} |  |
| Stables Harness Shop | 1 | {"building":"stable"} |  |
| Stables Horse Barn | 1 | {"building":"stable"} |  |
| Stables Mule Barn | 1 | {"building":"stable"} |  |
| Stables Office | 1 | {"building":"office"} |  |
| Stables Pack Tac Room | 1 | {"building":"stable"} |  |
| Stables Park Mule | 1 | {"building":"stable"} |  |
| Stables Pony Feeder | 1 | {"building":"stable"} |  |
| Stables Wagon Room | 1 | {"building":"stable"} |  |
| Tennis Courts | 1 | {"leisure":"pitch","sport":"tennis"} |  |
| Washburn Barn | 1 | {"building":"yes","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Wawona Campground | 2 | {"building":"yes"} | these are campground buildings, not the campground itself |
| Wawona Covered Bridge | 1 | {"building":"cabin","historic":"yes"} | see [this doc](https://www.nps.gov/yose/planyourvisit/upload/pyhc.pdf) |
| Wawona Gas Station | 1 | {"amenity":"fuel"} |  |
| Wawona General Store | 1 | {"shop":"general"} |  |
| Yosemite Lodge Bike Rental | 1 | {"shop":"general"} |  |

**Comment by jakecoolidge** [comment] 2016-04-17 21:20
Building tag translations:

| GIS Attribute | action | Places tag | comment |
| --- | --- | --- | --- |
| OBJECTID | removed |  |  |
| GeometryID | removed |  |  |
| Polygon_Type | removed |  |  |
| Is_Extent | removed |  |  |
| Is_Sensitive | removed |  |  |
| Source_Date | removed |  |  |
| Edit_Date | removed |  |  |
| Map_Method | removed |  |  |
| Map_Source | removed |  |  |
| Polygon_Notes | removed |  |  |
| Unit_Code | retained | "nps:unit_code":"yose" |  |
| Common_Name | retained | name |  |
| Admin_Type | removed |  |  |
| Federal_Entity_Type | removed |  |  |
| Building_FCode | removed |  |  |
| FMSS_ID | retained | nps:fmss_location_id |  |
| LCS_ID | removed |  |  |
| ASMIS_ID | removed |  |  |
| Park_ID | removed |  |  |
| Region_Code | removed |  |  |
| GlobalID | retained | nps:source_system_key_value | only ID field with a unique value for each feature |
|  | added | "nps:source_system":"RISD EGIS Building Polygons, accessed 2016-04-17" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |
|  | added | "building":"yes" |  |

**Comment by jakecoolidge** [comment] 2016-04-17 22:52
Only roads within park boundaries were retained. Roads tag translations:

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| CreateUser | removed |  |  |
| Distribute | removed |  |  |
| FeatureID | removed |  |  |
| GeometryID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| InPark | removed |  |  |
| IsSeasonal | retained | seasonal |  |
| OBJECTID | removed |  |  |
| OpenForUse | removed |  |  |
| ParkRoadCl | removed after populating highway tags, see table below |  |  |
| RegionCode | removed |  |  |
| RoadClass | removed |  | ParkRoadCl provides finer-grained detail |
| RoadLabel | retained | name |  |
| RoadLanes | removed |  | all 0 values |
| RoadName | removed |  | duplicate of RoadLabel |
| RoadStatus | removed |  |  |
| RoadSurface | retained | surface |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
| last_edit_1 | removed |  |  |
| last_edite | removed |  |  |

| ParkRoadCl value | Places preset | Places tag(s) | comment |
| --- | --- | --- | --- |
| Campground road | Access Road | {"highway":"service"} |  |
| Dirt road | Minor Road | {"highway":"unclassified"} | these were assigned RoadClass=Local |
| Gravel road | Minor Road | {"highway":"unclassified"} | these were assigned RoadClass=Local |
| NPS service road | Access Road | {"highway":"service"} |  |
| Parking lot or pullout | Parking Aisle | {"highway":"service","service":"parking_aisle"} |  |
| Primary road | Primary Road | {"highway":"primary"} |  |
| Secondary road | Secondary Road | {"highway":"secondary"} |  |
| Tertiary road (residential) | Residential Road | {"highway":"residential"} |  |
| Tunnel | Secondary Road (Tunnel) | {"highway":"secondary","tunnel":"yes"} | these were assigned RoadClass=Secondary |

**Comment by jakecoolidge** [comment] 2016-04-17 23:38
Trail tag translations:

GIS attribute | action | Places tag(s) | comment
--- | --- | --- | ---
ADA | retained | wheelchair
ATV | retained | 
AltName | removed
Bike | retained | bicycle
Comments | removed
Distribute | removed
FeatType | removed
GlobalID | retained | nps:source_system_key_value
Hike | retained | pedestrian
LoadDate | removed
Motorcycle | retained 
NonMotorized | retained
Notes | retained | nps:notes
OBJECTID | removed
PackOrSaddle | retained | horse
RegionCode | removed
Restrictio | removed 
SDE_STATE_ | removed
Shape_Leng | removed
TrailClass |
TrailName | 
TrailStatus |
TrailSurface | 
TrailType | 
UnitCode | retained | nps:unit_code
UnitName | removed
created_date | removed
created_user | removed
last_edited_data | removed
last_edited_user | removed
 | added | "nps:source_system":"PWR_NPS_Trails, accessed 2016-

**Comment by chadlawlis** [comment] 2016-04-18 16:14
All YOSE data currently in Places has been wiped via changeset 8816. I created a backup before wiping, available [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbX1ZBbG9aNDFNVTg) (`yose_pre_wipe_backup_20160418.osm`).

**Comment by chadlawlis** [comment] 2016-04-18 16:45
Roads seeded via changeset 8819. POIs seeded via changeset 8820. Buildings seeded via changeset 8821. OSM files available [here](https://drive.google.com/open?id=0B0AXEdn7N9KbVUJLcHpCUS01S28) (created by @jakecoolidge).

**Comment by jakecoolidge** [comment] 2016-04-21 20:36
@nateirwin to produce an extract of trails as GeoJSON using a node script and send it to me; I'm running up against a limit that prevents me from downloading the data from the service.

**Comment by jakecoolidge** [comment] 2016-04-22 21:36
Only trails within park boundaries seeded (deleted: trails with "Not in Park" included in the Comments field). Trails tag translations:

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| ADA | retained | wheelchair | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| ATV | retained | atv | see ADA |
| AltName | removed |  | mostly null values |
| Bike | retained | bicycle | see ADA |
| Comments | removed |  | captured surface tags based on some values prior to removal |
| Distribute | removed |  | deleted trails with Distribute=No |
| FeatType | removed |  |  |
| FeatureID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| Hike | retained | foot | see ADA |
| LoadDate | removed |  |  |
| Motorcycle | retained | motorcycle | see ADA |
| NonMotoriz | retained | motor_vehicle | see ADA |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| PackOrSadd | retained | horse | see ADA |
| RegionCode | removed |  |  |
| Restrictio | removed |  | duplicate of Distribute |
| TrailClass | removed |  |  |
| TrailName | retained | name | deleted names for trails named "none" |
| TrailStatu | removed |  | either "Existing" or null values only |
| TrailSurfa | retained | surface |  |
| TrailType | removed |  |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
| created_da | removed |  |  |
| created_us | removed |  |  |
| last_edi_1 | removed |  |  |
| last_edite | removed |  |  |
|  | added | "nps:source_system":"PWR_NPSTrails, accessed 2016-04-22" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

**Comment by jakecoolidge** [comment] 2016-04-22 21:41
Trails uploaded on changeset 8886. OSM file added to [this directory.](https://drive.google.com/open?id=0B0AXEdn7N9KbX1ZBbG9aNDFNVTg)

**Closed as completed by jakecoolidge** 2016-04-22 21:41 UTC
Labels: data-seed-request

**Comment by jakecoolidge** [comment] 2016-06-08 20:06
Added roads for the El Portal area using the translations listed above on changeset 9377 to match the YOSE custom mask of OSM data, see https://github.com/nationalparkservice/mapbox-studio-projects/pull/71/commits/e9c834fcb88520bf3d7db0b3ba0eb2d24bbb406c
