### ISSUE TITLE
Missing road/trail segments in CANY

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#30] opened 2015-04-28 19:54 UTC
Hey all, Just noticed some missing road & trail segments in CANY.  See attached.  Thanks, H
![capture](https://cloud.githubusercontent.com/assets/11545684/7378904/0da44446-edae-11e4-9095-589d4f0d668b.JPG)

Here's the area of concern...
![capture](https://cloud.githubusercontent.com/assets/11545684/7378940/4d78e0c2-edae-11e4-91ec-da305f84b691.JPG)

I'll pick these up when I send up the layers for places but thought you might want to fix it in Park Tiles for now.

**Comment by makella** [comment] 2015-04-28 19:58
I think this is relate to: https://github.com/nationalparkservice/places-data/issues/25 which is related to: nationalparkservice/park-tiles#144

Thanks for the additional information! We'll keep you updated as we implement the changes.

**Comment by nateirwin** [comment] 2015-06-18 17:04
Tagging as duplicate of #25 and closing for now. Track the status of that issue for updates.

**Closed as completed by nateirwin** 2015-06-18 17:04 UTC
Labels: duplicate
