### ISSUE TITLE
PWR Data Seed: PINN

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#790] opened 2016-08-29 18:33 UTC

**Comment by chadlawlis** [comment] 2016-08-29 18:34
Feature types by count:

| Feature type | Count | Query |
| --- | --- | --- |
| POI | 0 | [link](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_PointsOfInterest_Service/MapServer/0/query?where=UnitCode%3D%27PINN%27&returnCountOnly=true&f=pjson) |
| Roads | 13 | [link](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/1/query?where=UnitCode%3D%27PINN%27&returnCountOnly=true&f=pjson) |
| Trails | 28 | [link](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/0/query?where=UnitCode%3D%27PINN%27&returnCountOnly=true&f=pjson) |
| Parking | 17 | [link](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/2/query?where=UnitCode%3D%27PINN%27&returnCountOnly=true&f=pjson) |
| Buildings | 81 | [link](http://insidemapservices.nps.gov/arcgis/rest/services/Buildings/NPSBuildingsMapPWR/FeatureServer/0/query?where=Unit_Code=%27PINN%27&returnCountOnly=true&f=pjson) |

**Comment by chadlawlis** [comment] 2016-08-29 20:49
## POI

Source: [http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_PointsOfInterest_Service/MapServer/0/query?where=UnitCode%3D%27PINN%27&outFields=*&f=geojson](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_PointsOfInterest_Service/MapServer/0/query?where=UnitCode%3D%27PINN%27&outFields=*&f=geojson).

None.

## Roads

Source: [http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/1/query?where=UnitCode%3D%27PINN%27&outFields=*&f=geojson](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/1/query?where=UnitCode%3D%27PINN%27&outFields=*&f=geojson).

Translated keys/values (PWR value only specified if not free form):

| PWR key | PWR value | Places tag |
| --- | --- | --- |
| UnitCode | PINN | nps:unit_code = pinn |
| RoadName | (free form text) | name = (free form text) |
| RoadClass | Local | highway = residential |
| RoadClass | Primary | highway = primary |
| RoadClass | Private | highway = road, access = private |
| RoadClass | Service | highway = service |
| RoadSurface | Asphalt | surface = asphalt |
| RoadLanes | 1 | lanes = 1 |

**Primary key:**

| nps:source_system | nps:source_system_key | nps:source_system_key_value |
| --- | --- | --- |
| PWR_EditTRANS_Service | GlobalID | {globalid_value} |

## Trails

Source: [http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/0/query?where=UnitCode%3D%27PINN%27&outFields=*&f=geojson](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/0/query?where=UnitCode%3D%27PINN%27&outFields=*&f=geojson).

Translated keys/values (PWR value only specified if not free form):

| PWR key | PWR value | Places tag |
| --- | --- | --- |
| UnitCode | PINN | nps:unit_code = pinn |
| TrailName | (free form text) | name = (free form text) |
| TrailClass | Class 2 | tracktype = grade 4 |
| TrailClass | Class 3 | tracktype = grade 3 |
| TrailClass | Class 4 | tracktype = grade 2 |
| TrailClass | Class 5 | tracktype = grade 1 |
| TrailSurface | Concrete | surface = concrete |
| TrailSurface | Native Material | surface = ground |
| Hike | 1 | foot = yes |
| PackOrSaddle | 2 | horse = no |
| Bike | 2 | bicycle = no |

**Primary key:**

| nps:source_system | nps:source_system_key | nps:source_system_key_value |
| --- | --- | --- |
| PWR_EditTRANS_Service | GlobalID | {globalid_value} |

## Parking

Source: [http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/2/query?where=UnitCode%3D%27PINN%27&outFields=*&f=geojson](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_EditTRANS_Service/FeatureServer/2/query?where=UnitCode%3D%27PINN%27&outFields=*&f=geojson).

Translated keys/values (PWR value only specified if not free form):

| PWR key | PWR value | Places tag |
| --- | --- | --- |
| UnitCode | PINN | nps:unit_code = pinn |
| ParkingName | (free form text) | name = (free form text) |
| ParkingSurface | Asphalt | surface = asphalt |

**Primary key:**

| nps:source_system | nps:source_system_key | nps:source_system_key_value |
| --- | --- | --- |
| PWR_EditTRANS_Service | GlobalID | {globalid_value} |

## Buildings

Source: [http://insidemapservices.nps.gov/arcgis/rest/services/Buildings/NPSBuildingsMapPWR/FeatureServer/0/query?where=Unit_Code=%27PINN%27&outfields=*&f=json](http://insidemapservices.nps.gov/arcgis/rest/services/Buildings/NPSBuildingsMapPWR/FeatureServer/0/query?where=Unit_Code=%27PINN%27&outfields=*&f=json).

Translated keys/values (PWR value only specified if not free form):

| PWR key | PWR value | Places tag |
| --- | --- | --- |
| Unit_Code | PINN | nps:unit_code = pinn |
| Common_Name | (free form text) | name = (free form text) |
| FMSS_ID | (integer) | nps:fmss_id = (integer) |

**Primary key:**

| nps:source_system | nps:source_system_key | nps:source_system_key_value |
| --- | --- | --- |
| NPSBuildingsMapPWR | GlobalID | {globalid_value} |

**Comment by jakecoolidge** [comment] 2016-08-30 20:46
### Trails tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| ADA | retained | wheelchair | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| ATV | retained | atv | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| Bike | retained | bicycle | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| Comments | retained | nps:notes |  |
| CreateDate | removed |  |  |
| Distribute | removed |  | trails marked "Distribute:No" were not imported |
| EditDate | removed |  |  |
| FeatType | removed |  |  |
| FeatureID | removed |  |  |
| Flag |  |  |  |
| FlagCommen |  |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| Hike | retained | foot | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| LoadDate | removed |  |  |
| Motorcycle | retained | motorcycle | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| NonMotoriz | removed |  | all marked 1 (yes), consistent with highway:path |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| PackOrSaddle | retained | horse | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| RegionCode | removed |  |  |
| TrailClass | retained | see comment above |  |
| TrailName | retained | name |  |
| TrailStatus | removed |  | all listed as 'Existing' |
| TrailSurface | retained | surface |  |
| TrailType | removed |  |  |
| UnitCode | retained | nps:unit_code | 'SEQU' and 'KICA' replaced with 'seki' |
| UnitName | removed |  |  |
| VisAccess | removed |  |  |
| XYError | removed |  |  |
| created_date | removed |  |  |
| created_user | removed |  |  |
| last_edited_date | removed |  |  |
|  | added | "highway":"path" |  |
|  | added | "nps:source_system":"PWR EditTRANS Service, accessed 2016-08-30" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

### Roads tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| AssetID | removed |  |  |
| FeatureID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| InPark | removed |  |  |
| MapMethod | removed |  |  |
| MapSource | removed |  |  |
| OBJECTID | removed |  |  |
| OpenForUse | removed |  |  |
| ParkRoadClass | removed |  | duplicate of RoadClass, uses coded domains |
| RegionCode | removed |  |  |
| RoadClass | removed after populating highway tags, see table below |  |  |
| RoadLabel | name |  |  |
| RoadLanes | retained | lanes |  |
| RoadName | removed |  | duplicate of RoadLabel |
| RoadStatus | removed |  |  |
| RoadSurface | retained | surface |  |
| RouteID | retained |  |  |
| RouteNumber | retained | ref |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
|  | added | "nps:source_system":"PWR_Roads_Service, accessed 2016-06-02" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

| RoadClass value | Places preset | Places tag(s) | comment |
| --- | --- | --- | --- |
| Local | Minor Road | {"highway":"unclassified"} |  |
| Primary | Primary Road | {"highway":"primary"} |  |
| Private | Private Road | {"highway":"road","access":"private"} |  |
| Service | Access Road | {"highway":"service"} |  |

### Parking Areas tag translations

| GIS Attribute | action | Places tag | comment |
| --- | --- | --- | --- |
| AssetID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| MapSource | removed |  | all marked "RIP Cycle5" |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| ParkingName | retained | name |  |
| ParkingSurface | retained | surface |  |
| RegionCode | removed |  |  |
| RIP_Surface | removed |  |  |
| RouteID | retained | ref |  |
| RouteNumber | removed |  |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
|  | added | "nps:source_system":"PWR_VehicularParking_Service, accessed 2016-06-03" |  |
|  | added | "amenity":"parking" |  |

### Buildings tag translations

| GIS Attribute | action | Places tag | comment |
| --- | --- | --- | --- |
| Admin_Type | removed |  | Buildings marked "Admin_Type"="PRIVATE" given the tag "access":"private" |
| Building_ID | removed |  |  |
| Common_Name | retained | name |  |
| Edit_Date | removed |  |  |
| FMSS_ID | retained | nps:fmss_location_id |  |
| Federal_En | removed |  |  |
| GeometryID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| Is_Extant | removed |  | All were marked 'Y' |
| Is_Sensitive | removed |  | All were marked 'N' |
| LCS_ID | removed |  |  |
| Map_Method | removed |  |  |
| Map_Source | removed |  |  |
| OBJECTID | removed |  |  |
| Park_ID | removed |  |  |
| Polygon_Notes | removed |  |  |
| Polygon_Type | removed |  |  |
| Region_Code | removed |  |  |
| Source_Date | removed |  |  |
| Unit_Code | retained | "nps:unit_code":"yose" |  |
|  | added | "nps:source_system":"RISD EGIS Building Polygons, accessed 2016-04-17" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |
|  | added | "building":"yes" |  |

**Comment by jakecoolidge** [comment] 2016-08-30 21:00
Uploaded on changeset 10531.

**Closed as completed by jakecoolidge** 2016-08-30 21:00 UTC
Labels: data-seed-request, pwr
