### ISSUE TITLE
PWR Data Seed: DEVA Trails, Buildings

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#314] opened 2015-12-08 16:25 UTC
Sandy from PWR requested that we seed the following data for Death Valley using her published services:
- Trails
- Buildings (from facilities)

Feature Server: [http://inppwcagis01:6080/arcgis/rest/services/PWR](http://inppwcagis01:6080/arcgis/rest/services/PWR)

**Comment by jakecoolidge** [comment] 2016-05-09 22:48
DEVA roads and trails wiped on changeset 9068. Backup of pre-wipe data stored [here.](https://drive.google.com/open?id=0B8kRL6psDWmZaHRCSEc0WUdLZDA)

Buildings for this park unit not available in RISD EGIS buildings dataset.

POIs not imported due to data inconsistencies. In some cases, the POIFEATTYPE is populated with a recognizable value (ex., "Campground"), in other cases, this field is left null, and in others, a code (ex., "56") is given. For some, but not all, features with null feature type values, the type is indicated by the name.

### Trails

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| ADA | retained | wheelchair | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| ATV | retained | atv | see ADA |
| Bike | retained | bicycle | see ADA |
| Comments | removed |  |  |
| Distribute | removed |  | all trails marked Distribute=Yes |
| EditDate | removed |  |  |
| FeatType | removed |  |  |
| FeatureID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| Hike | retained | foot | see ADA |
| MapMethod | removed |  |  |
| MapSource | removed |  |  |
| Motorcycle | retained | motorcycle | see ADA |
| NonMotoriz | retained | motor_vehicle | see ADA |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| PackOrSadd | retained | horse | see ADA |
| RegionCode | removed |  |  |
| Restrictio | removed |  | all marked "Unrestricted" |
| TrailClass | removed |  |  |
| TrailName | retained | name | deleted names for trails named "none" |
| TrailStatu | removed |  | all trails marked "Existing" |
| TrailSurfa | retained | surface | "Native Material" converted to "dirt"; "TrailSurfa"="Other" is a boardwalk |
| TrailType | removed |  |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
| VisAccess | retained | access | for VisAccess='Closed', access=no; for VisAccess='Open', no tag added |
| XYError | removed |  |  |
| created_da | removed |  |  |
| created_us | removed |  |  |
| last_edi_1 | removed |  |  |
| last_edite | removed |  |  |
|  | added | "nps:source_system":"PWR_NPSTrails, accessed 2016-05-09" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

### Roads

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| AssetID | removed |  |  |
| CreateDate | removed |  |  |
| CreateUser | removed |  |  |
| Distribute | retained | "Internal Only" access=no; all others "Public" |  |
| EditDate | removed |  |  |
| EditUser | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| GroupCode | removed |  |  |
| InPark | removed |  | all marked "Yes" |
| LocationID | removed |  |  |
| Maintainer | removed |  |  |
| MapMethod | removed |  |  |
| MapSource | removed |  |  |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| ParkRoadCl | removed |  | RoadClass appears to have better data |
| RegionCode | removed |  |  |
| Restrictio | removed |  |  |
| RoadAltName | retained | alt_name |  |
| RoadClass | removed after populating highway tags | see below |  |
| RoadLabel | retained | name |  |
| RoadLanes | retained | lanes |  |
| RoadName | removed |  | duplicate of RoadLabel |
| RoadOneWay | retained | one_way | for segments marked "Against Digitized", road segment directions were reversed |
| RoadStatus | removed |  | temporarily closed roads given the access=no tag |
| RoadSurface | retained | surface |  |
| RouteID | retained | ref |  |
| RouteNumber | removed |  |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
| created_da | removed |  |  |
| created_us | removed |  |  |
| last_edit_1 | removed |  |  |
| last_edite | removed |  |  |
|  | added | "nps:source_system"="PWR_Roads_Service, accessed 20160509" |  |
|  | added | "nps:source_system_key"="GlobalID" |  |

| RoadClass value | Places preset | Places tag(s) | comment |
| --- | --- | --- | --- |
| 4WD | Four-Wheel Drive Road | {"highway":"road"; "4wd_only":"yes"} |  |
| Local | Minor Road | {"highway":"unclassified"} |  |
| Private | Minor Road | {"highway":"unclassified"; "access":"private"} |  |
| Secondary | Secondary Road | {"highway":"secondary"} |  |
| Service | Access Road | {"highway":"service"} |  |
| Unknown | Unknown Road | {"highway":"road"} |  |

**Comment by jakecoolidge** [comment] 2016-06-01 17:51
John at DEVA has provided a version of the POI data with standardized types defined in the "UserTag" field; POI dataset stored [here.](https://drive.google.com/open?id=0B8kRL6psDWmZaHRCSEc0WUdLZDA) This data will eventually replace what is currently on PWR's server. Existing POI data (87 features) removed on changeset 9353. New POI data (226 features) uploaded on changeset 9354 with the following tag translations:

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| Contributor | removed |  |  |
| Description | removed |  |  |
| FeatureType | removed |  | see UserTag below |
| MapMethod | removed |  |  |
| Name | retained | name |  |
| Notes | retained | nps:notes |  |
| UnitCode | retained | nps:unit_code | values converted to lowercase |
| UnitName | removed |  |  |
| UserTag | converted | see table below |  |
|  | added | "nps:source_system":"DEVA_POI_rev.gdb" |  |
|  | added | "nps:source_system_key":"none" |  |

| UserTag value | Places preset | Places tag(s) | comment |
| --- | --- | --- | --- |
| Airport | Airport | {"aeroway":"aerodrome"} |  |
| Automated Fee Machine | Fee Booth | {"barrier":"toll_booth"} |  |
| Campground | Campground | {"tourism":"camp_site"} |  |
| Drinking Water | Potable Water | {"amenity":"drinking_water"} |  |
| Dump Station | Dump Station | {"amenity":"sanitary_dump_station"} |  |
| Entrance Station | Entrance Station | {"barrier":"entrance"} |  |
| Food Service | Food Service | {"amenity":"food_court"} |  |
| Gas Station | Gas Station | {"amenity":"fuel"} |  |
| Headquarters | Headquarters | {"building":"office","office":"government","function":"headquarters"} | name: "Ash Meadows National Wildlife Refuge" |
| Information | Information | {"tourism":"information"} |  |
| Lodge | Lodging | {"tourism":"hotel"} | a review of lodging options on nps.gov/deva suggests these locations fit the category of hotels, as opposed to wilderness huts |
| Museum | Museum | {"tourism":"museum"} |  |
| Park Headquarters | Headquarters | {"building":"office","office":"government","function":"headquarters"} |  |
| Picnic Area | Picnic Area | {"tourism":"picnic_site"} |  |
| Point of Interest | Point of Interest | {"tourism":"yes"} |  |
| Ranger Station | Ranger Station | {"amenity":"ranger_station"} |  |
| Restroom | Restroom | {"amenity":"toilets"} |  |
| Store | Store | {"shop":"general"} |  |
| Telephone | Telephone | {"amenity":"telephone"} |  |
| Trailhead | Trailhead | {"highway":"trailhead"} |  |
| Visitor Center | Visitor Center | {"tourism":"information","information":"office"} |  |

**Closed as completed by jakecoolidge** 2016-06-01 17:51 UTC
Labels: data-seed-request
