### ISSUE TITLE
PWR Data Seed: SEKI Roads, Trails, Buildings

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#304] opened 2015-12-08 16:07 UTC
Sandy from PWR requested that we seed the following data for Sequoia & Kings Canyon using her published services:
- Roads
- Trails
- Buildings (from facilities)

Feature Server: [http://inppwcagis01:6080/arcgis/rest/services/PWR](http://inppwcagis01:6080/arcgis/rest/services/PWR)

**Comment by jakecoolidge** [comment] 2016-06-02 22:41
Data in Places prior to wipe-and-replace stored [here](https://drive.google.com/open?id=0B8kRL6psDWmZZW05S212LUpOam8). Data removed on changeset 9538 (see last section, PWR and Park Atlas POIs). Due to the large amount of data involved, each theme was uploaded on its own changset: 
- Trails: 9359
- Roads: 9360
- Parking areas: 9361
- Buildings: 9362
- Points of Interest: 9363

### Trails tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| AltName | retained | alt_name |  |
| CreateDate | removed |  |  |
| Distribute | removed |  | trails marked "Distribute:No" were not imported |
| EditDate | removed |  |  |
| FeatType | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| Hike | retained | foot | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| MapMethod | removed |  |  |
| MapSource | removed |  |  |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| PackOrSaddle | retained | horse | see Hike above |
| RegionCode | removed |  |  |
| Restriction | removed |  | redundant with Distribute |
| SourceDate | removed |  |  |
| SourceScale | removed |  |  |
| TrailClass | removed |  |  |
| TrailName | retained | name |  |
| TrailStatus | removed |  | all listed as 'Existing' |
| TrailSurface | retained | surface |  |
| TrailType | removed |  |  |
| UnitCode | retained | nps:unit_code | 'SEQU' and 'KICA' replaced with 'seki' |
| UnitName | removed |  |  |
| XYError | removed |  |  |
| created_date | removed |  |  |
| created_user | removed |  |  |
| last_edited_date | removed |  |  |
|  | added | "highway":"path" |  |
|  | added | "nps:source_system":"PWR_NPSTrails, accessed 2016-06-02" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

### Roads tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| created_date | removed |  |  |
| created_user | removed |  |  |
| CreateDate | removed |  |  |
| CreateUser | removed |  |  |
| Distribute | removed |  |  |
| EditDate | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| GroupCode | removed |  |  |
| InPark | removed |  | only roads marked "InPark=Yes" were imported, with the exception of Generals Hwy between Grant Grove and Lodgepole Visitor Centers and Redwood Mtn Rd |
| IsSeasonal | retained | seasonal |  |
| last_edit_1 | removed |  |  |
| last_edite | removed |  |  |
| Maintainer | removed |  |  |
| MapLabel | removed |  | mostly null values, otherwise duplicate of RoadName |
| MapMethod | removed |  |  |
| MapSource | removed |  |  |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| OpenForUse | removed |  |  |
| ParkRoadClass | removed after populating highway tags, see table below |  |  |
| RegionCode | removed |  |  |
| Restriction | removed |  |  |
| RoadClass | removed |  | duplicate of ParkRoadClass |
| RoadLabel | removed |  |  |
| RoadName | retained | name |  |
| RoadStatus | removed |  |  |
| RoadSurface | retained | surface |  |
| RouteNumber | retained | ref |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
|  | added | "nps:source_system":"PWR_Roads_Service, accessed 2016-06-02" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

| ParkRoadCl value | Places preset | Places tag(s) | comment |
| --- | --- | --- | --- |
| Local | Minor Road | {"highway":"unclassified"} |  |
| Primary | Primary Road | {"highway":"primary"} |  |
| Private | Private Road | {"highway":"road","access":"private"} |  |
| Secondary | Secondary Road | {"highway":"secondary"} |  |

### Parking Areas tag translations

| GIS Attribute | action | Places tag | comment |
| --- | --- | --- | --- |
| AssetID | removed |  |  |
| Distribute | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| GroupCode | removed |  |  |
| InPark | removed |  | all marked "Yes" |
| IsSeasonal | retained | seasonal |  |
| last_edited_date | removed |  |  |
| last_edited_user | removed |  |  |
| MapSource | removed |  | all marked "RIP Cycle5" |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| OpenForUse | removed |  | parking lots marked "NONPUBLIC" given the tag access:no |
| ParkingName | retained | name |  |
| ParkingSurface | retained | surface |  |
| RegionCode | removed |  |  |
| Restriction | removed |  |  |
| RIP_Surface | removed |  |  |
| RouteID | retained | ref |  |
| RouteNumber | removed |  |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
|  | added | "nps:source_system":"PWR_VehicularParking_Service, accessed 2016-06-03" |  |
|  | added | "amenity":"parking" |  |

### Buildings tag translations

| GIS Attribute | action | Places tag | comment |
| --- | --- | --- | --- |
| Admin_Type | removed |  | Buildings marked "Distribute"="Internal Only" AND "Admin_Type"="PRIVATE" given the tag "access":"private"; "Distribute"="Internal Only" AND "Admin_Type"="FEDERAL" given the tag "access":"no" |
| Building_FCode | removed |  |  |
| Building_ID | removed |  |  |
| Common_Name | retained | name |  |
| Distribute | removed |  | Buildings marked "Internal Only" (627 out of 796 extant buildings) given access tags, see Admin_Type |
| Edit_Date | removed |  |  |
| Federal_Entity_Type | removed |  |  |
| FMSS_ID | retained | nps:fmss_location_id |  |
| GeometryID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| Is_Extant | removed |  | Buildings marked 'N' were removed |
| Is_Sensitive | removed |  | All were marked 'N', except for three with null values |
| LCS_ID | removed |  |  |
| Map_Method | removed |  |  |
| Map_Source | removed |  |  |
| OBJECTID | removed |  |  |
| Park_ID | removed |  |  |
| Polygon_Notes | removed |  | In 68 instances, this field provided a general name (ex., 'Shed') for otherwise nameless features |
| Polygon_Type | removed |  |  |
| Region_Code | removed |  |  |
| Source_Date | removed |  |  |
| Unit_Code | retained | "nps:unit_code":"yose" |  |
|  | added | "nps:source_system":"RISD EGIS Building Polygons, accessed 2016-04-17" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |
|  | added | "building":"yes" |  |

### Points of Interest tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| DISTRIBUTE | removed |  | all marked "Public" |
| GlobalID | retained | nps:source_system_key_value |  |
| GROUPCODE | removed |  |  |
| ISEXTANT | removed |  | all marked "Yes" |
| ISSEASONAL | retained | seasonal |  |
| OBJECTID | removed |  |  |
| POIFEATTYPE | removed |  | all marked "Vicinity Point" |
| POINAME | retained | name |  |
| POITYPE | see table below |  |  |
| REGIONCODE | removed |  |  |
| RESTRICTION | removed |  | all marked "Unrestricted" |
| UNITCODE | retained | nps:unit_code |  |
| UNITNAME | removed |  |  |
|  | added | "nps:source_system":"PWR_NPS_PointsOfInterest, accessed 2016-06-02" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

| POITYPE value | Places preset | Places tag(s) | comment |
| --- | --- | --- | --- |
| Campground | Campground | {"tourism":"camp_site"} |  |
| Entrance Station | Entrance Station | {"barrier":"entrance"} |  |
| Gas Station | Gas Station | {"amenity":"fuel"} |  |
| Gate | Gate | {"barrier":"gate"} |  |
| Lodge | Lodging | {"tourism":"hotel"} | more traditional "hotel" type accommodations vs. alpine hut-type lodges |
| Picnic Area | Picnic Area | {"tourism":"picnic_site"} |  |
| Ranger Station | Ranger Station | {"amenity":"ranger_station"} |  |
| Restroom | Restroom | {"amenity":"toilets"} |  |
| Store | Store | {"shop":"general"} |  |
| Telephone | Telephone | {"amenity":"telephone"} |  |
| Trailhead | Trailhead | {"highway":"trailhead"} |  |
| Visitor Center | Visitor Center | {"tourism":"information","information":"office"} |  |

### PWR and extant Places POIs

Extant POI data in Places is derived from national datasets seeded in 2014, Park Atlas data seeded in the summer of 2015, and a small number of features added via Places Submit. This data was replaced with PWR data, with the exception of the following POI types that are not represented in the PWR data:

Park Atlas data (June 2015) 
- Viewpoint
- Campsite
- Litter Receptacle
- Potable Water
- Recycling
- Bus Stop / Shuttle Stop
- Campfire Ring 

National GIS Program data (June 2014)
- Point of Interest
- Park Headquarters

Places Submit entry
- Museum

**Closed as completed** 2016-06-03 19:48 UTC
Labels: data-seed-request
