### ISSUE TITLE
PWR Data Seed: OLYM Roads, Trails, Buildings

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#301] opened 2015-12-07 20:00 UTC
Sandy from PWR requested that we seed the following data using her published services:
- Roads
- Trails
- Buildings (from facilities)

Feature Server: [http://inppwcagis01:6080/arcgis/rest/services/PWR](http://inppwcagis01:6080/arcgis/rest/services/PWR)

**Comment by jakecoolidge** [comment] 2016-11-09 20:43
OLYM and PWR GIS staff confirmed on 2016-11-08 that the data for this park on the following services is ready for import to Places:

Points of Interest
[http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_PointsOfInterest_Service/FeatureServer/0/query?where=UnitCode%3D%27OLYM%27&outFields=*&f=geojson](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_PointsOfInterest_Service/FeatureServer/0/query?where=UnitCode%3D%27OLYM%27&outFields=*&f=geojson)

Roads
[http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_Roads_Service/FeatureServer/0/query?where=UnitCode%3D%27OLYM%27&outFields=*&f=geojson](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_Roads_Service/FeatureServer/0/query?where=UnitCode%3D%27OLYM%27&outFields=*&f=geojson)

Trails
[http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_Trails_Service/FeatureServer/0/query?where=UnitCode%3D%27OLYM%27&outFields=*&f=geojson](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_Trails_Service/FeatureServer/0/query?where=UnitCode%3D%27OLYM%27&outFields=*&f=geojson)

Parking Areas
[http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_VehicularParking_Service/FeatureServer/0/query?where=UnitCode%3D%27OLYM%27&outFields=*&f=geojson](http://inppwcagis01:6080/arcgis/rest/services/pwr/PWR_VehicularParking_Service/FeatureServer/0/query?where=UnitCode%3D%27OLYM%27&outFields=*&f=geojson)

Buildings
[http://insidemapservices.nps.gov/arcgis/rest/services/Buildings/NPSBuildingsMapPWR/FeatureServer/0/query?where=Unit_Code='OLYM'&outfields=*&f=json](http://insidemapservices.nps.gov/arcgis/rest/services/Buildings/NPSBuildingsMapPWR/FeatureServer/0/query?where=Unit_Code='OLYM'&outfields=*&f=json)

Back up of pre-import Places data stored [here.](https://drive.google.com/open?id=0B8kRL6psDWmZOGVXYlQ4MlVlVms)

### Points of Interest tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| CREATEDATE | removed |  |  |
| DISTRIBUTE | removed |  | all marked 'Public' |
| EDITDATE | removed |  |  |
| FEATUREID | removed |  |  |
| GEOMETRYID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| ISEXTANT | removed |  | all marked 'Yes' |
| OBJECTID | removed |  |  |
| PLACESID | retained | nps:places_id |  |
| POINAME | retained | name |  |
| POITYPE | see table below |  |  |
| REGIONCODE | removed |  |  |
| TAGS | removed |  | replaced by new tags |
| UNITCODE | retained | "nps:unit_code":"olym" |  |
| last_edited_date | removed |  |  |
| last_edited_user | removed |  |  |
|  | added | "nps:source_system":"PWR Points of Interest Service, accessed 2016-11-09" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

| POITYPE value | Places preset | Places tag(s) | comment |
| --- | --- | --- | --- |
| Backcountry Campsite | Primitive Camping | "tourism":"camp_site"; "camp_site":"pitch"; "backcountry":"yes" |  |
| Boat Launch | Boat Launch | "leisure":"slipway" |  |
| Campground | Campground | "tourism":"campsite" |  |
| Entrance Station | Entrance Station | "barrier":"entrance" |  |
| Food Service | Food Service | "amenity":"food_court" |  |
| Gas Station - Boat Only | none available, suggesting Store (see comment) | "shop":"general" | In OSM, harbor amenities like fuel are typically tagged with the harbor, see [this.](https://wiki.openstreetmap.org/wiki/Seamarks/Harbours) Upon closer inspection, fuel for small craft appears to be one item for sale at a general store at this location, hence I'm suggesting the Store preset. |
| Information | Information | "tourism":"information" |  |
| Lodging | Lodging | "tourism":"hotel" |  |
| Office | Headquarters | "building":"office"; "office":"government"; "function":"headquarters" | location is named 'Headquarters' |
| Parking Lot | Parking Lot | "amenity":"parking" |  |
| Picnic Area | Picnic Area | "tourism":"picnic_site" |  |
| Point of Interest | Point of Interest | "tourism":"yes" |  |
| Ranger Station | Ranger Station | "amenity":"ranger_station" |  |
| Restroom | Restroom | "amenity":"toilets" |  |
| Shelter | Shelter | "amenity":"shelter"; "building":"hut" |  |
| Swimming Area | Swimming Area | "sport":"swimming" |  |
| Trailhead | Trailhead | "highway":"trailhead" |  |
| Visitor Center | Visitor Center | "tourism":"information"; "information":"office" |  |
| Wheelchair Accessible | Wheelchair Accessible | "wheelchair":"yes" |  |

### Road tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| Distribute | removed |  | all marked 'Public' |
| FeatureID | removed |  |  |
| GeometryID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| InPark | removed |  |  |
| Notes | removed |  | duplicate of Surface |
| OBJECTID | removed |  |  |
| RegionCode | removed |  |  |
| RoadLabel | removed |  | duplicate of RoadName |
| RoadName | retained | name |  |
| RoadSurface | retained | surface | values: Gravel, Asphalt |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
| last_edited_date | removed |  |  |
| last_edited_user | removed |  |  |
|  | added | "nps:source_system":"PWR Roads Service, accessed 2016-11-09" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |
|  | added | "highway":"unclassified" | Road classifications were not provided |

### Trail tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| ADA | retained | wheelchair | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| ATV | retained | atv | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| AltName | retained | alt_name |  |
| Bike | retained | bicycle | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| Comments | removed |  |  |
| Distribute | removed |  | all marked 'Yes' |
| FeatType | removed |  |  |
| FeatureID | removed |  |  |
| Flag | removed |  |  |
| FlagComment | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| Hike | retained | foot | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| LoadDate | removed |  |  |
| MapMethod | removed |  |  |
| MapSource | removed |  |  |
| Motorcycle | retained | motorcycle | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| NonMotorized | removed |  |  |
| Notes | nps:notes |  |  |
| OBJECTID | removed |  |  |
| PackOrSaddle | retained | horse | PWR coded domains: 1=yes, 2=no (0=unknown, not used) |
| RegionCode | removed |  |  |
| TrailClass | removed |  |  |
| TrailName | retained | name |  |
| TrailStatus | removed |  |  |
| TrailSurfa | retained | surface |  |
| TrailType | removed |  |  |
| UnitCode | retained | nps:unit_code |  |
| VisAccess | retained | access:yes | marked 'Open' or _null_ |
| created_date | removed |  |  |
| created_user | removed |  |  |
| last_edited_date | removed |  |  |
| last_edited_user | removed |  |  |
|  | added | "highway":"path" |  |
|  | added | "nps:source_system":"PWR Trails Service, accessed 2016-08-24" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

### Parking area tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| AssetID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| MapSource | removed |  |  |
| Notes | retained | nps:notes |  |
| OBJECTID | removed |  |  |
| OpenForUse | removed |  |  |
| ParkingName | retained | name |  |
| ParkingSurface | retained | surface |  |
| RIP_Surface | removed |  |  |
| RegionCode | removed |  |  |
| RouteID | removed |  |  |
| UnitCode | retained | nps:unit_code |  |
| UnitName | removed |  |  |
| last_edited_date | removed |  |  |
| last_edited_user | removed |  |  |
|  | added | "nps:source_system":"PWR Vehicular Parking Service, accessed 2016-11-09" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

### Building tag translations

| GIS attribute | action | Places tag(s) | comment |
| --- | --- | --- | --- |
| Admin_Type | removed |  | all marked 'Federal' |
| Building_F | removed |  |  |
| Building_I | removed |  |  |
| Common_Name | retained | name |  |
| Distribute | removed |  | all marked 'Public' |
| Edit_Date | removed |  |  |
| FMSS_ID | retained | nps:fmss_location_id |  |
| Federal_Entity | removed |  |  |
| Geometry_ID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| Is_Extant | removed |  | all marked 'Y' |
| IS_Sensitive | removed |  | all marked 'N' |
| LCS_ID | removed |  |  |
| Map_Method | removed |  |  |
| Map_Source | removed |  |  |
| OBJECTID | removed |  |  |
| Park_ID | removed |  |  |
| Polygon_No | removed |  |  |
| Polygon_Ty | removed |  |  |
| Region_Code | removed |  |  |
| Source_Date | removed |  |  |
| Unit_Code | retained | nps:unit_code |  |
|  | added | "building":"yes" |  |
|  | added | "nps:source_system":"RISD EGIS Building Polygons, accessed 2016-08-24" |  |
|  | added | "nps:source_system_key":"GlobalID" |  |

**Comment by jakecoolidge** [comment] 2016-11-09 21:46
Uploaded on changeset 10711

**Closed as completed by jakecoolidge** 2016-11-09 21:46 UTC
Labels: data-seed-request, pwr

**Comment by ryanjhodge** [comment] 2017-02-01 00:48
Hey @jakecoolidge, there's two waterfalls in the POI dataset that didn't get translated as such: soleduck falls and marymere falls. 

I'd add the tag myself but PWR GIS has decided to lock down the Places Editor :frowning_face:

**Comment by jakecoolidge** [comment] 2017-02-01 15:14
I fixed this, @ryanjhodge--it may take a day or so to show up in PT3. Thanks for catching that!
