### ISSUE TITLE
CartoDB `points_of_interest` tags not synced with Places

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#618] opened 2016-03-03 23:13 UTC
Some of the tags and associated types in our [`points_of_interest` CartoDB table](https://nationalparkservice.cartodb.com/u/nps/tables/points_of_interest) are not synced with what is live in Places. For example, using the following query:

``` sql
SELECT *
FROM points_of_interest
WHERE unit_code = 'grte'
AND (type = 'Locale' or type = 'Park District')
ORDER BY type, name;
```

5 of the 7 returned show up as type "Park District" with tag "place=village" which is both no longer supported by Places and also not what shows up in Editor. Each of these 5 are type "Locale" with tag "place=locality", which is correct.

@jimmyrocks, you mentioned you need to update the table in `places_pgs`? Assigning to you - thanks!

**Comment by jimmyrocks** [comment] 2016-03-04 12:10
It looks like the pgs table was already updated. The problem is with 2500
records that were added on to cartodb 2015-09-23T19:38:07Z. These records
were added manually and are apparently not linking back. I'll need to
re-add them to cartodb programatically.

**Comment by jimmyrocks** [comment] 2016-03-07 17:11
I ran an update and all missing points should be fixed

**Closed as completed by jimmyrocks** 2016-03-07 17:11 UTC
Labels: bug, places-points-of-interest
