### ISSUE TITLE
PWR Data Seed: LAVO Roads, Trails, Buildings, Parking Areas

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#300] opened 2015-12-07 19:52 UTC
Sandy from PWR requested that we seed the following data using her published services:
- Roads
- Trails
- Buildings (from facilities)
- Parking Areas

Feature Server [http://inppwcagis01:6080/arcgis/rest/services/PWR](http://inppwcagis01:6080/arcgis/rest/services/PWR)

**Comment by jakecoolidge** [comment] 2016-04-27 21:45
Existing roads, buildings, and points of interest deleted using Changeset 8962, which failed to close. Backup of old data stored in [lavo_pre_wipe_backup_20160427.osm](https://drive.google.com/open?id=0B8kRL6psDWmZd1J2ZkJrdll2Szg).

**Comment by jakecoolidge** [comment] 2016-04-27 22:01
Buildings: only Distribute=Public buildings included. Tag translations can be found on [this issue.](https://github.com/nationalparkservice/places-data/issues/303) Uploaded on Changeset 8964.

**Comment by jakecoolidge** [comment] 2016-04-27 22:43
Only roads marked InPark=Yes and Distribute=Public included. Tag translations can be found on [this issue](https://github.com/nationalparkservice/places-data/issues/303), with a couple notable exceptions:

ParkRoadClass was not available for this park. RoadClass was translated instead.
RoadClass=Service > highway=service (Service Road)
RoadClass=Local > highway=unclassified (Minor Road)

RouteNumber translated to ref

RoadOneWay was deleted, as the only values are "Two-Way", which is the default in Places.

Tag translations for trails can also be found in the issue linked above. 

Roads and trails uploaded on Changeset 8966.

**Comment by jakecoolidge** [comment] 2016-04-27 23:22
POI tag translations:

| GIS attribute | action | Places tag | comment |
| --- | --- | --- | --- |
| CREATEDATE | removed |  |  |
| CREATEUSER | removed |  |  |
| DISTRIBUTE | removed |  | all marked "Public" |
| FEATUREID | removed |  |  |
| GEOMETRYID | removed |  |  |
| GlobalID | retained | nps:source_system_key_value |  |
| MAPMETHOD | removed |  |  |
| MAPSOURCE | removed |  |  |
| NOTES | nps:notes |  |  |
| OBJECTID | removed |  |  |
| POIALTNAME | retained | alt_name |  |
| POIFEATTYPE | removed |  | all marked "Center point" |
| POILABEL | removed |  | duplicate of POINAME |
| POINAME | retained | name |  |
| POITTYPE | retained | see table below |  |
| REGIONCODE | removed |  |  |
| RESTRICTIO | removed |  | all marked "Unrestricted" |
| UNITCODE | retained | "nps:unit_code"="lavo" |  |
| UNITNAME | removed |  |  |
| XYERROR | removed |  |  |
|  | added | "nps:source_system"="PWR_NPS_PointsOfInterest, accessed 2016-04-27" |  |
|  | added | "nps:source_system_key"="GlobalID" |  |

| POITYPE value | Places tag(s) |
| --- | --- |
| Amphitheater | {"amenity":"theatre","theatre:type":"amphi"} |
| Boat Launch | {"leisure":"slipway"} |
| Campground | {"tourism":"camp_site"} |
| Corral | {"building":"stable"} |
| Dump Station | {"amenity":"sanitary_dump_station"} |
| Entrance Station | {"barrier":"entrance"} |
| Fire Lookout | {"man_made":"tower"} |
| Gas Station | {"amenity":"fuel"} |
| Headquarters | {"building":"office","office":"government","function":"headquarters"} |
| Historic Cabin | {"building":"cabin","historic":"yes"} |
| Information | {"tourism":"information"} |
| Lodging | {"tourism":"hotel"} |
| Parking Lot | {"amenity":"parking"} |
| Peak | {"natural":"peak"} |
| Picnic Area | {"tourism":"picnic_site"} |
| Point of Interest | {"tourism":"yes"} |
| Ranger Station | {"amenity":"ranger_station"} |
| Restroom | {"amenity":"toilets"} |
| Store | {"shop":"general"} |
| Trailhead | {"highway":"trailhead"} |
| Viewpoint | {"tourism":"viewpoint"} |
| Visitor Center | {"tourism":"information","information":"office"} |
| Waterfall | {"waterway":"waterfall"} |

Uploaded on Changeset 8967.

**Closed as completed by jakecoolidge** 2016-04-27 23:22 UTC
Labels: data-seed-request
